### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by unshorn** [pietrobraione/jbse#18]
I'm experiencing an error building the project. There is a class cast error and class file version  (for the files in test/resources) errors while running the tests. I'm building with Oracle's JDK 1.8.

**Comment by pietrobraione** [comment]
Hi, sorry for the late answer. What branch did you check out?

**Comment by pietrobraione** [comment]
I also experienced some glitches in running the tests when the project is loaded in Eclipse. Please try these steps:
- do mvn clean eclipse:clean compile eclipse:eclipse (either from console or from an Eclipse Maven launch config)
- refresh the Eclipse project
- now try mvn test

**Comment by unshorn** [comment]
I'm sorry I missed your reply. I was trying to run the tests on the command line on the master branch. Re-cloned the repo and it works now. Thank you.
