### ISSUE TITLE
JBSE Installation

### ISSUE THREAD

**Issue by pabloloyola** [pietrobraione/jbse#2]
Hi, 
I'm trying to install JBSE.  I'm using Ubuntu  and  Eclipse 3.8.1. I Installed the JavaCC plugin and I got the error reported on the docs. When I try to manually add the paths to the jars, I noticed that the Java CC global options asks me for a path to the javacc jar file and the jtb jar file. I can find the first one  inside plugin folder, but  the jtb jar file is missing. I know this is not strictly a JBSE problem, but can you tell me which version of the javacc plugin you are using (I am using 1.5.32)?
Thank you

**Comment by pietrobraione** [comment]
Hi Pablo. My version of the javacc plugin is also 1.5.32. JBSE doesnt' need jtb to compile, so it is ok if jtb is missing from your setup. Feel free to contact me again if you need support while setting up JBSE.
Best,
Pietro

**Comment by pabloloyola** [comment]
Hi, thanks.  Which version of Eclipse are you using ?

**Comment by pietrobraione** [comment]
I always use the latest, currently mars.2.
