### ISSUE TITLE
SettingParser

### ISSUE THREAD

**Issue by monperrus** [pietrobraione/jbse#4]
Hi,
I don't use Eclipse. Is there a way to generate the files from SettingParser.jj using ant on the command-line?
Thanks,
--Martin

**Comment by pietrobraione** [comment]
Hi Martin, there is an ant file in the JBSE project (contributed by a colleague of mine) but it does invoke javacc, I think. 
Unfortunately I don’t know anything about ant, so I cannot be of help. The command line to compile the parser with javacc is:

java -classpath /path/to/javacc-5.0.jar javacc SettingsParser.jj 

The file SettingsParser.jj is in src/jbse/apps/settings.
Best,
Pietro
